version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule: { interval: "weekly" }
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule: { interval: "weekly" }
    ignore:
      - dependency-name: "@vitejs/plugin-react"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }
