changelog:
  categories:
    - title: "🚀 Features"
      labels: ["feat"]
    - title: "🐛 Bug Fixes"
      labels: ["fix"]
    - title: "🧰 Maintenance"
      labels: ["chore", "docs", "refactor", "test"]
