default_language_version:
  node: system

repos:
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        exclude: ^ui/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^ui/
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort
        args: [--profile=black]
        exclude: ^ui/
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.32.0
    hooks:
      - id: eslint
        args: [--fix]
        files: ^ui/
        types_or: [javascript, jsx, ts, tsx]
        exclude: ^ui/node_modules/
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^ui/
        exclude: ^ui/node_modules/
