version: '3.8'
services:
  vllm:
    image: vllm/vllm:latest
  slm:
    image: nvcr.io/nim/llama3-8b:1.0
    profiles: ["inference"]
    command: ["--api","openai","--decoder-only","true","--dtype","fp8","--max-input-len","8192","--max-requests","96"]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              device_ids: ["7"]
