# Copyright (c) 2025 CPUTER Inc.
# SPDX-License-Identifier: MIT
# Project Codename: NAESTRO (Orchestrator)

receivers:
  otlp: { protocols: { http: {}, grpc: {} } }
exporters:
  logging: {}
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]
