datasets:
  - name: InfoSeek
    description: >-
      InfoSeek deep research benchmarking suite covering research tree
      construction, compound QA, and reward-finetuning trajectory splits
      used to stress multi-hop planning and BrowseComp-Plus readiness.
    enabled: true
    path: hf://datasets/Lk123/InfoSeek
    tasks:
      - research_tree_construction
      - compound_question_answering
      - trajectory_reward_finetuning
    k_samples: 256
