defaults:
  deterministic: false

datasets:
  - name: InfoSeek
    description: >-
      InfoSeek deep research benchmarking suite covering research tree
      construction, compound QA, and reward-finetuning trajectory splits
      used to stress multi-hop planning and BrowseComp-Plus readiness.
    enabled: true
    path: hf://datasets/Lk123/InfoSeek
    tasks:
      - research_tree_construction
      - compound_question_answering
      - trajectory_reward_finetuning
    k_samples: 256

suites:
  golden_prompts:
    description: >-
      Golden prompt regression suite ensuring deterministic replayability
      across high-signal prompts before enabling self-improvement loops.
    datasets:
      - InfoSeek
    deterministic: true

  canary_smoke:
    description: >-
      Canary smoke tests mirroring production guardrails; deterministic to
      guarantee reproducible gating signals prior to rollout.
    datasets:
      - InfoSeek
    deterministic: true

  load_tests:
    description: >-
      Stress and soak tests focused on throughput and concurrency. These
      intentionally allow nondeterministic execution to reflect production
      variability.
    datasets:
      - InfoSeek
    deterministic: false
