routers:
  - name: ling-flash-2.0
    display_name: Ling-flash-2.0 router
    description: >-
      Placeholder for the Ling-flash-2.0 mixture-of-experts router lane
      (100B total parameters with ~6.1B activated, delivering ~7× dense-model
      efficiency and 128K-context throughput) until integration is complete.
    enabled: false
    tags:
      - moe
      - experimental
  - name: magistral-1.2-small
    display_name: Magistral-1.2-small router
    description: >-
      Placeholder for the Magistral-1.2 small-form-factor router lane
      (optimized for low-latency guardrail and filtering duties) until the
      production integration is wired up.
    provider: magistral
    family: magistral-1.2
    params: 8000000000
    enabled: false
    tags:
      - magistral
      - router
      - preview
  - name: magistral-1.2-24b
    display_name: Magistral-1.2-24B router
    description: >-
      Placeholder for the Magistral-1.2 24B router lane (full-capacity
      deployment supporting long-context reasoning bursts) until production
      rollout is complete.
    provider: magistral
    family: magistral-1.2
    params: 24000000000
    enabled: false
    tags:
      - magistral
      - router
      - preview
