name: Naestro CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev]
      - name: Ruff
        run: >-
          ruff check naestro packs examples
          tests/test_debate_basic.py tests/test_roles_registry.py
          tests/test_message_bus.py tests/test_governor.py
          tests/test_router_selection.py
          tests/packs/trading/test_backtest_smoke.py
          tests/packs/trading/test_pipeline_debate_gate.py
          tests/conftest.py tests/training/__init__.py
      - name: Black
        run: >-
          black --check naestro packs examples
          tests/test_debate_basic.py tests/test_roles_registry.py
          tests/test_message_bus.py tests/test_governor.py
          tests/test_router_selection.py
          tests/packs/trading/test_backtest_smoke.py
          tests/packs/trading/test_pipeline_debate_gate.py
          tests/conftest.py tests/training/__init__.py
      - name: Mypy
        run: mypy --strict naestro packs examples
      - name: Pytest
        run: pytest
      - name: Run examples
        run: |
          python examples/debate_quickstart.py
          python examples/governed_pipeline.py
          python examples/routing_profiles.py
          python examples/cli.py
          python packs/trading/examples/aapl_demo.py
      - name: Upload debate traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: naestro-runs
          path: .naestro_runs/**
          if-no-files-found: ignore
