name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ui:
    name: UI (Node 22.x)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: 'ui/package-lock.json'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck || true

      - name: Build
        run: npm run build

      - name: Test (CI)
        env:
          CI: 'true'
        run: npm run test:ci
