name: CI
on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  ui:
    runs-on: ubuntu-latest
    container: node:22-bullseye
    defaults: { run: { working-directory: ui } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-ui-npm-${{ hashFiles('ui/package-lock.json') }}
          restore-keys: ${{ runner.os }}-ui-npm-
      - uses: actions/cache@v4
        with:
          path: ui/node_modules/.vite
          key: ${{ runner.os }}-vite-${{ hashFiles('ui/package-lock.json') }}
          restore-keys: ${{ runner.os }}-vite-
      - run: npm ci
      - run: npm run lint --if-present
      - run: npm run typecheck --if-present
      - run: npm run build --if-present
      - run: npm run test:ci --if-present
        env: { CI: "true" }
