name: CI
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci
        if: hashFiles('package-lock.json') != ''
      - run: npm run lint --if-present
      - run: npm run typecheck --if-present
      - run: npm test --if-present
  providers-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm i ajv ajv-formats yaml
      - run: node scripts/validate-providers.js
        continue-on-error: false
  ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - name: Install UI deps
        working-directory: ./ui
        run: npm ci
        if: hashFiles('ui/package-lock.json') != ''
      - name: Lint
        working-directory: ./ui
        run: npm run lint --if-present
      - name: Build
        working-directory: ./ui
        run: npm run build --if-present
