name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install root requirements (optional)
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No root requirements.txt"
          fi

      - name: Install gateway requirements (optional)
        run: |
          if [ -f src/gateway/requirements.txt ]; then
            pip install -r src/gateway/requirements.txt
          else
            echo "No gateway requirements"
          fi

      - name: Install orchestrator requirements (optional)
        run: |
          if [ -f src/orchestrator/requirements.txt ]; then
            pip install -r src/orchestrator/requirements.txt
          else
            echo "No orchestrator requirements"
          fi

      - name: Sanity compile (non-fatal)
        run: |
          python -m compileall -q src/gateway || true
          python -m compileall -q src/orchestrator || true

      - name: Run tests if present (non-fatal)
        run: |
          if [ -f pytest.ini ] || [ -f pyproject.toml ] || [ -d tests ]; then
            pip install pytest
            pytest -q
          else
            echo "No tests configured — skipping"
          fi
