name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CI: "true"
  TZ: "UTC"
  LC_ALL: "C.UTF-8"
  LANG: "C.UTF-8"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # No cache here — avoids lockfile errors at repo root
      - name: Setup Node 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          check-latest: true

      # Root lint (only runs if a lockfile + script exists)
      - name: Install (root) if lockfile
        if: ${{ hashFiles('package-lock.json', 'npm-shrinkwrap.json', 'yarn.lock') != '' }}
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          elif [ -f yarn.lock ]; then
            corepack enable || true
            yarn install --frozen-lockfile
          fi
      - name: Lint (root)
        run: npm run lint --if-present

      # Server lint
      - name: Install (server) if lockfile
        if: ${{ hashFiles('server/package-lock.json', 'server/npm-shrinkwrap.json', 'server/yarn.lock') != '' }}
        working-directory: ./server
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          elif [ -f yarn.lock ]; then
            corepack enable || true
            yarn install --frozen-lockfile
          fi
      - name: Lint (server)
        if: ${{ hashFiles('server/package.json') != '' }}
        working-directory: ./server
        run: npm run lint --if-present

      # UI lint
      - name: Install (ui) if lockfile
        if: ${{ hashFiles('ui/package-lock.json', 'ui/npm-shrinkwrap.json', 'ui/yarn.lock') != '' }}
        working-directory: ./ui
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          elif [ -f yarn.lock ]; then
            corepack enable || true
            yarn install --frozen-lockfile
          fi
      - name: Lint (ui)
        if: ${{ hashFiles('ui/package.json') != '' }}
        working-directory: ./ui
        run: npm run lint --if-present

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          check-latest: true

      # Root typecheck
      - name: Install (root) if lockfile
        if: ${{ hashFiles('package-lock.json', 'npm-shrinkwrap.json', 'yarn.lock') != '' }}
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          elif [ -f yarn.lock ]; then
            corepack enable || true
            yarn install --frozen-lockfile
          fi
      - name: Typecheck (root)
        run: npm run typecheck --if-present

      # Server typecheck
      - name: Install (server) if lockfile
        if: ${{ hashFiles('server/package-lock.json', 'server/npm-shrinkwrap.json', 'server/yarn.lock') != '' }}
        working-directory: ./server
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          elif [ -f yarn.lock ]; then
            corepack enable || true
            yarn install --frozen-lockfile
          fi
      - name: Typecheck (server)
        if: ${{ hashFiles('server/package.json') != '' }}
        working-directory: ./server
        run: npm run typecheck --if-present

      # UI typecheck
      - name: Install (ui) if lockfile
        if: ${{ hashFiles('ui/package-lock.json', 'ui/npm-shrinkwrap.json', 'ui/yarn.lock') != '' }}
        working-directory: ./ui
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          elif [ -f yarn.lock ]; then
            corepack enable || true
            yarn install --frozen-lockfile
          fi
      - name: Typecheck (ui)
        if: ${{ hashFiles('ui/package.json') != '' }}
        working-directory: ./ui
        run: npm run typecheck --if-present

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          check-latest: true

      # Root build
      - name: Install (root) if lockfile
        if: ${{ hashFiles('package-lock.json', 'npm-shrinkwrap.json', 'yarn.lock') != '' }}
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          elif [ -f yarn.lock ]; then
            corepack enable || true
            yarn install --frozen-lockfile
          fi
      - name: Build (root)
        run: npm run build --if-present

      # Server build
      - name: Install (server) if lockfile
        if: ${{ hashFiles('server/package-lock.json', 'server/npm-shrinkwrap.json', 'server/yarn.lock') != '' }}
        working-directory: ./server
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          elif [ -f yarn.lock ]; then
            corepack enable || true
            yarn install --frozen-lockfile
          fi
      - name: Build (server)
        if: ${{ hashFiles('server/package.json') != '' }}
        working-directory: ./server
        run: npm run build --if-present

      # UI build
      - name: Install (ui) if lockfile
        if: ${{ hashFiles('ui/package-lock.json', 'ui/npm-shrinkwrap.json', 'ui/yarn.lock') != '' }}
        working-directory: ./ui
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          elif [ -f yarn.lock ]; then
            corepack enable || true
            yarn install --frozen-lockfile
          fi
      - name: Build (ui)
        if: ${{ hashFiles('ui/package.json') != '' }}
        working-directory: ./ui
        run: npm run build --if-present

  ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          check-latest: true

      - name: Install (ui) if lockfile
        if: ${{ hashFiles('ui/package-lock.json', 'ui/npm-shrinkwrap.json', 'ui/yarn.lock') != '' }}
        working-directory: ./ui
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          elif [ -f yarn.lock ]; then
            corepack enable || true
            yarn install --frozen-lockfile
          else
            echo "No lockfile in ./ui; skipping install."
          fi

      - name: Lint (ui)
        if: ${{ hashFiles('ui/package.json') != '' }}
        working-directory: ./ui
        run: npm run lint --if-present

      - name: Build (ui)
        if: ${{ hashFiles('ui/package.json') != '' }}
        working-directory: ./ui
        run: npm run build --if-present

      - name: Test (ui)
        if: ${{ hashFiles('ui/package.json') != '' }}
        working-directory: ./ui
        run: npm test --if-present