name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: ui/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test:ui
        if: ${{ hashFiles('ui/src/**/*.{test,spec}.{js,jsx,ts,tsx}') != '' }}

  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"
          cache-dependency-path: |
            requirements.lock
            scripts/requirements.txt
      - run: pip install -r requirements.lock -r scripts/requirements.txt
      - name: Flake8
        run: |
          if command -v flake8 >/dev/null 2>&1; then
            flake8
          else
            echo "flake8 not installed"
          fi
      - name: Pytest
        run: |
          if command -v pytest >/dev/null 2>&1; then
            pytest
          else
            echo "pytest not installed"
          fi

  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
