name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ui:
    name: UI (lint • typecheck • build • test)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node 22.x
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint --if-present
      - name: Typecheck
        run: npm run typecheck --if-present
      - name: Build
        run: npm run build --if-present
      - name: Test (jsdom)
        env:
          CI: 'true'
        run: |
          if npm run | grep -q "test:ui"; then
            npm run test:ui
          elif npm run | grep -q "test"; then
            npm test
          else
            echo "No tests defined, skipping."
          fi
