concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
name: Codex Exec (Node 22)
on:
  workflow_dispatch:
    inputs:
      command:
        description: "Shell to run in ui/ (Node 22 container)"
        required: true
        default: "pnpm install && pnpm build && pnpm test:ci"

jobs:
  exec:
    runs-on: ubuntu-latest
    container: node:22-bullseye
    defaults: { run: { working-directory: ui } }
    steps:
      - uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: ${{ inputs.command }}
        env: { CI: "true" }
