name: PR Title

on:
  pull_request_target:

permissions:
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amannn/action-semantic-pull-request@v5
        with:
          autoFix: true
          config: commitlint.config.cjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

