concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
name: PR Title (Conventional Commits)

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  pr-title:
    name: Validate PR title with commitlint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Use Node 22
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Lint PR title
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.cjs
          helpURL: https://www.conventionalcommits.org/en/v1.0.0/
