concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
name: Recheck CI
on:
  pull_request:
    types:
      - labeled
jobs:
  trigger:
    if: github.event.label.name == 'recheck'
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch CI workflow
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ci.yml',
              ref: context.payload.pull_request.head.ref
            })
