name: Reference Link Check
on:
  pull_request:
    paths:
      - "docs/**/*.md"
      - "REFERENCES.md"
      - "ROADMAP.md"
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install --no-audit --no-fund
      - name: Check links
        run: |
          set -euo pipefail
          files="$(git ls-files 'docs/**/*.md' 'REFERENCES.md' 'ROADMAP.md')"
          echo "$files" | tr ' ' '\n' | while read -r f; do
            echo "🔗 Checking $f"
            npx markdown-link-check -q -c .mlc.config.json "$f"
          done
      - name: Upload summary
        if: always()
        run: echo "Link check completed" >> $GITHUB_STEP_SUMMARY
